const EMAIL_SUBJECTS = {
    FORGOT_PASSWORD: "FORGOT PASSWORD",
    EMAIL_VERIFICATION: "EMAIL VERIFICATION",
    WELCOME_EMAIL: "WELCOME",
    PAYMENT_SUCCESSFUL: "PAYMENT SUCCESSFUL",
    PAYMENT_FAILED: "PAYMENT FAILED",
    INVITATION: "INVITATION",
    NEW_TRANSACTION: "NEW TRANSACTION INITIATED",
}

module.exports = {
    EMAIL_SUBJECTS,
}