const CONDITION = {
    USED: "USED",
    BRAND_NEW: "BRAND_NEW"
}

const AVAILABILITY = {
    OPEN: "OPEN",
    SOLD: "SOLD",
    CLOSED: "CLOSED"
}

const ITEM_CATEGORY = {
    PETS: "PETS",
    ELECTRONICS: "ELECTRONICS",
    PHONES_TABLETS: "PHONES_TABLETS",
    FUNITURE_APPLIANCES: "FUNITURE_APPLIANCES",
    SPORTS_ARTS_OUTDOORS: "SPORTS_ARTS_OUTDOORS",
    HEALTH_BEAUTY: "HEALTH_BEAUTY",
    FASHION: "FASHION",
    PROPERTY: "PROPERTY",
    VEHICLES: "VEHICLES",
    BABIES_KIDS: "BABIES_KIDS",
    AGRICULTURE_FOOD: "AGRICULTURE_FOOD",
    COMMERCIAL_EQUPMENT_TOOLS:  "COMMERCIAL_EQUPMENT_TOOLS",
    REPAIR_CONSTRUCTION: "REPAIR_CONSTRUCTION",
}


// SUB CATEGORIES
const PETS_CATEGORY = {
    BIRDS: "BIRDS",
    CATS_KITTENS: "CATS_KITTENS",
    DOGS_PUPPIES: "DOGS_PUPPIES",
    FISH: "FISH",
    PET_ACCESSORIES: "PET_ACCESSORIES",
    REPTILES: "REPTILES",
    OTHERS: "OTHERS",
}

const ELECTRONICS_CATEGORY = {
    ACCESSORIES_ELECTRONIC_SUPPLIES: "ACCESSORIES_ELECTRONIC_SUPPLIES",
    LAPTOP_COMPUTERS: "LAPTOP_COMPUTERS",
    TV_DVD_EQUIPMENT: "TV_DVD_EQUIPMENT",
    AUDIO_MUSIC_EQUIPMENT: "AUDIO_MUSIC_EQUIPMENT",
    COMPUTER_ACCESSORIES: "COMPUTER_ACCESSORIES",
    COMPUTER_HARDWARE: "COMPUTER_HARDWARE",
    COMPUTER_MONITORS: "COMPUTER_MONITORS",
    HEADPHONES: "HEADPHONES",
    NETWORKING_PRODUCTS: "NETWORKING_PRODUCTS",
    PHOTO_VIDEO_CAMERAS: "PHOTO_VIDEO_CAMERAS",
    PRINTERS_SCANNERS: "PRINTERS_SCANNERS",
    SECURITY_SURVEILLANCE: "SECURITY_SURVEILLANCE",
    SOFTWARE: "SOFTWARE",
    VIDEO_GAMES: "VIDEO_GAMES",
    VIDEO_GAME_CONSOLES: "VIDEO_GAME_CONSOLES",
}

const FUNITURE_APPLIANCES_CATEGORY = {
    FUNITURE: "FUNITURE",
    GARDEN_SUPPLIES: "GARDEN_SUPPLIES",
    HOME_ACCESSORIES: "VIDEO_GAME_CONSOLES",
    HOME_APPLIANCES: "HOME_APPLIANCES",
    KITCHEN_APPLIANCES: "KITCHEN_APPLIANCES",
    KITCHEN_COOKWARE: "KITCHEN_COOKWARE",
    HOUSEHOLD_CHEMICALS: "HOUSEHOLD_CHEMICALS",
}

const HEALTH_BEAUTY_CATEGORY = {
    BATH_BODY: "BATH_BODY",
    FRAGRANCES: "FRAGRANCES",
    HAIR_BEAUTY: "HAIR_BEAUTY",
    MAKE_UP: "MAKE_UP",
    SEXUAL_WELLNESS: "SEXUAL_WELLNESS",
    SKINCARE: "SKINCARE",
    TOBACCO_ACCESSORIES: "TOBACCO_ACCESSORIES",
    TOOLS_ACCESSORIES: "TOOLS_ACCESSORIES",
    VITAMINS_SUPPLEMENTS: "VITAMINS_SUPPLEMENTS",
}

const FASHION_CATEGORY = {
    BAGS: "BAGS",
    CLOTHING: "CLOTHING",
    JEWELLERY: "JEWELLERY",
    SHOES: "SHOES",
    WATCHES: "WATCHES",
    WEDDING_WEAR_ACCESSORIES: "WEDDING_WEAR_ACCESSORIES",
}

const SPORTS_ARTS_OUTDOORS_CATEGORY = {
    ARTS_CRAFTS: "ARTS_CRAFTS",
    BOOKS_GAMES: "BOOKS_GAMES",
    CAMPING_GEAR: "CAMPING_GEAR",
    CD_DVDS: "CD_DVDS",
    WATCHES: "WATCHES",
    MUSICAL_INSTRUMENTS_GEAR: "MUSICAL_INSTRUMENTS_GEAR",
    SPORTS_EQUIPMENT: "SPORTS_EQUIPMENT",
}

const PHONES_TABLETS_CATEGORY = {
    MOBILE_PHONES: "MOBILE_PHONES",
    ACCESSORIES_PHONES_TABLETS: "ACCESSORIES_PHONES_TABLETS",
    SMART_WATCHES_TRACKERS: "SMART_WATCHES_TRACKERS",
    TABLETS: "TABLETS",
}

const VEHICLE_CATEGORY = {
    CARS: "CARS",
    BUSES_MICROBUSES: "BUSES_MICROBUSES",
    HEAVY_EQUIPMENT: "HEAVY_EQUIPMENT",
    MOTORBIKES_SCOOTERS: "MOTORBIKES_SCOOTERS",
    TRUCKS_TRAILERS: "TRUCKS_TRAILERS",
    VEHICLE_PARTS_ACCESSORIES: "VEHICLE_PARTS_ACCESSORIES",
    WATERCRAFT_BOATS: "WATERCRAFT_BOATS",
}

const BABIES_KIDS_CATEGORY = {
    ACCESSORIES: "ACCESSORIES",
    CHILD_CARE: "CHILD_CARE",
    CHILD_CLOTHING: "CHILD_CLOTHING",
    CHILD_FUNITURE: "CHILD_FUNITURE",
    CHILD_GEAR_SAFETY: "CHILD_GEAR_SAFETY",
    MATERNITY_PREGNANCY: "MATERNITY_PREGNANCY",
    PLATGROUND_EQUIPMENT: "PLATGROUND_EQUIPMENT",
}

const AGRICULTURE_FOOD_CATEGORY = {
    FARM_MACHINE_EQUIPMENT: "ACCESSORIES",
    FEEDS_SUPPLEMENTS_SEEDS: "CHILD_CARE",
    FARM_ANIMALS: "CHILD_CLOTHING",
    MEALS_DRINKS: "CHILD_FUNITURE",
}

const COMMERCIAL_EQUPMENT_TOOLS_CATEGORY = {
    INDUSTRIAL_OVENS: "INDUSTRIAL_OVENS",
    MANUFACTURING_EQUIPMENT: "MANUFACTURING_EQUIPMENT",
    MANUFACTURING_MATERIALS_TOOLS: "MANUFACTURING_MATERIALS_TOOLS",
    PRINTING_EQUIPMENTS: "PRINTING_EQUIPMENTS",
    RESTURANT_CATERING_EQUIPMENT: "RESTURANT_CATERING_EQUIPMENT",
    SAFETYWEAR_EQUIPMENT: "SAFETYWEAR_EQUIPMENT",
    SALON_EQUIPMENT: "SALON_EQUIPMENT",
    STAGE_LIGHTING_EFFECTS: "STAGE_LIGHTING_EFFECTS",
    STATIONERY: "STATIONERY",
    STORE_EQUIPMENT: "STORE_EQUIPMENT",
}

const REPAIR_CONSTRUCTION_CATEGORY = {
    BUILDING_MATERIALS: "BUILDING_MATERIALS",
    DOORS: "DOORS",
    ELECTRICAL_EQUIPMENT: "ELECTRICAL_EQUIPMENT",
    ELECTRICAL_HAND_TOOLS: "ELECTRICAL_HAND_TOOLS",
    HAND_TOOLS: "HAND_TOOLS",
    MEASURING_LAYOUT_TOOLS: "MEASURING_LAYOUT_TOOLS",
    PLUMBING_WATER_SUPPLY: "PLUMBING_WATER_SUPPLY",
    SALON_EQUIPMENT: "SALON_EQUIPMENT",
    SOLAR_ENRYGY: "SOLAR_ENRYGY",
    WINDOWS: "WINDOWS",
}

module.exports ={
    ITEM_CATEGORY,
    PETS_CATEGORY,
    FASHION_CATEGORY,
    VEHICLE_CATEGORY,
    BABIES_KIDS_CATEGORY,
    ELECTRONICS_CATEGORY,
    HEALTH_BEAUTY_CATEGORY,
    PHONES_TABLETS_CATEGORY,
    AGRICULTURE_FOOD_CATEGORY,
    REPAIR_CONSTRUCTION_CATEGORY,
    SPORTS_ARTS_OUTDOORS_CATEGORY,
    COMMERCIAL_EQUPMENT_TOOLS_CATEGORY,
    AVAILABILITY,
    CONDITION
}